### ISSUE TITLE
安装后在LiteLoaderQQNT的管理器页面不显示此插件且无法单独关闭，还会干涉其他插件的正常使用（如LLAPI）

### ISSUE THREAD

**Issue by RingingVolcano** [xinyihl/LiteLoaderQQNT-JustF5#2]
如题

**Comment by xinyihl** [comment]
首先这个插件很久没有更新了它适配的是0.x版本的liteloader，这个插件我不建议普通用户使用，另这个插件的实现方式很简单理论上不会对其他插件造成影响，因此我可能不会解决你的问题。
最后感谢你的使用&建议。

**Comment by RingingVolcano** [comment]
> 首先这个插件很久没有更新了它适配的是0.x版本的liteloader，这个插件我不建议普通用户使用，另这个插件的实现方式很简单理论上不会对其他插件造成影响，因此我可能不会解决你的问题。 最后感谢你的使用&建议。

好的 因为1.x版本LiteLoader的插件商店最近收录了这个插件 直接一键安装后在1.x上会出现一些问题 所以发了这个issue反馈
