### ISSUE TITLE
[BUG] F5刷新后不正常显示

### ISSUE THREAD

**Issue by fgr178707** [xinyihl/LiteLoaderQQNT-JustF5#3]
![image](https://github.com/xinyihl/LiteLoaderQQNT-JustF5/assets/109357981/1c811378-6dcf-4d0d-a3fa-56add1c20a38)
在登录界面，也可以F5刷新

**Comment by fgr178707** [comment]
> ![image](https://private-user-images.githubusercontent.com/109357981/317265699-1c811378-6dcf-4d0d-a3fa-56add1c20a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Njg5NjMsIm5iZiI6MTcxMTc2ODY2MywicGF0aCI6Ii8xMDkzNTc5ODEvMzE3MjY1Njk5LTFjODExMzc4LTZkY2YtNGQwZC1hM2ZhLTU2YWRkMWMyMGEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwMzE3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDdlMzg2ZjBlZDEwODhjMDJiYmQ4MjM2MGJlNDJiN2NhMjM0NjNmM2YzMTczOTcxYWM5NTdkODQzNzFmZGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6oU3s88fYLeK81BSGeyFIqxe7V1o33Dq6kA1711BdL0) 
![image](https://github.com/xinyihl/LiteLoaderQQNT-JustF5/assets/109357981/21fed9ec-2aa5-468f-af3d-eb63a540e689)

在登录界面，也可以F5刷新

**Comment by xinyihl** [comment]
正常现象，该插件针对所有窗口都应生效，
至于不正常显示很抱歉我无法复现你的问题，
请尝试关闭其他所有插件后再次尝试。

**Comment by fgr178707** [comment]
> 正常现象，该插件针对所有窗口都应生效， 至于不正常显示很抱歉我无法复现你的问题， 请尝试关闭其他所有插件后再次尝试。
> 请尝试关闭其他所有插件后再次尝试。

尝试过了 也不行  Chii DevTools F12 SHIFT+CTRL+R 也有这个问题
我怀疑应该是qq的问题
